#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo '❌ 🚨 Uh-oh! We have a code style emergency on our hands! 😱 Prettier Check Failed. Don't panic, though. 💪 Let's run npm run format, perform some life-saving styling maneuvers, and rescue that commit from style disaster. 🚒🔥💼';
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

npm run build ||
(
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅🚀 Mission success! The countdown is over, and its time to launch our commit to the coding cosmos. Buckle up and let our code soar to new heights of awesomeness! 🚀🌌✨';